// const API_BASE = 'http://172.20.30.148:8000';
const API_BASE = 'http://127.0.0.1:8000';
const state = { devices: [], refreshTimer: null, refreshInProgress: false, deviceSignature: null, editDeviceId: null, activeTab: 'summary', ipSearch: '', ipStatus: 'all', history: [], previousStatuses: new Map() };
const $ = (id) => document.getElementById(id);
const elements = { refreshButton: $('refresh-btn'), addDeviceButton: $('add-device-btn'), indicator: $('auto-refresh-indicator'), connectionLabel: $('connection-label'), lastUpdated: $('last-updated'), deviceModal: $('device-modal'), modalTitle: $('device-modal-title'), deviceForm: $('device-form'), formStatus: $('form-status'), deleteModal: $('delete-confirm-modal'), deleteName: $('delete-device-name'), deleteId: $('delete-device-id'), ipSearch: $('ip-search'), ipStatus: $('ip-status-filter') };

function escapeHtml(value) { return String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;'); }
function formatDateTime(value) { if (!value) return 'Never'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Never' : new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(date); }
function formatShortDate(value) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(date); }
function isIp(value) { return /^\d{1,3}(?:\.\d{1,3}){3}$/.test(String(value || '').trim()); }
function subnetOf(value) { return isIp(value) ? `${value.split('.').slice(0, 3).join('.')}.0/24` : 'Unassigned / label'; }
function statusClass(status) { return ['online', 'offline', 'unknown'].includes(status) ? status : 'unknown'; }
function statusPill(status) { const safeStatus = statusClass(status); return `<span class="status-pill ${safeStatus}"><span class="status-dot ${safeStatus}"></span>${safeStatus}</span>`; }

async function fetchJson(url, options = {}) { const response = await fetch(`${API_BASE}${url}`, { headers: { 'Content-Type': 'application/json' }, ...options }); const contentType = response.headers.get('content-type') || ''; const payload = contentType.includes('application/json') ? await response.json() : await response.text(); if (!response.ok) throw new Error(typeof payload === 'string' ? payload : payload.detail || 'Request failed'); return payload; }
function groupedSubnets() { const groups = new Map(); state.devices.forEach((device) => { const subnet = subnetOf(device.ip_address); if (!groups.has(subnet)) groups.set(subnet, { subnet, total: 0, online: 0, offline: 0, unknown: 0, devices: [] }); const group = groups.get(subnet); group.total += 1; group[statusClass(device.status)] += 1; group.devices.push(device); }); return [...groups.values()].sort((a, b) => b.total - a.total); }
function updateMetrics() { const devices = state.devices; const labels = devices.filter((device) => !isIp(device.ip_address)).length; const online = devices.filter((device) => device.status === 'online').length; const offline = devices.filter((device) => device.status === 'offline').length; const unknown = devices.length - online - offline; const subnets = groupedSubnets(); const used = devices.length ? Math.round((online + offline) / devices.length * 100) : 0; $('summary-total').textContent = devices.length; $('summary-reserved').textContent = 0; $('summary-subnets').textContent = subnets.filter((item) => item.subnet !== 'Unassigned / label').length; $('summary-used').textContent = `${used}%`; $('summary-online').textContent = online; $('summary-offline').textContent = offline; $('summary-unknown').textContent = unknown; $('summary-labels').textContent = labels; $('subnet-count-label').textContent = `${subnets.length} subnets`; $('availability-used').textContent = `${used}%`; $('status-online').textContent = online; const availabilityParts = [{ label: 'Used', value: online + offline, color: '#39b77d' }, { label: 'Unknown', value: unknown, color: '#f4ae58' }]; const statusParts = [{ label: 'Online', value: online, color: '#2eb67d' }, { label: 'Offline', value: offline, color: '#ef5b5b' }, { label: 'Unknown', value: unknown, color: '#f4ae58' }]; renderDonut('availability-chart', availabilityParts); renderDonut('status-chart', statusParts); renderLegend('availability-legend', availabilityParts); renderLegend('status-legend', statusParts); renderSubnetChart(subnets); $('alert-count').textContent = offline; $('alert-summary').textContent = offline ? `${offline} active offline alert${offline === 1 ? '' : 's'}` : 'No active alerts'; }
function renderDonut(id, parts) { const total = parts.reduce((sum, part) => sum + part.value, 0); let offset = 0; const gradient = total ? parts.map((part) => { const start = offset / total * 100; offset += part.value; return `${part.color} ${start}% ${offset / total * 100}%`; }).join(', ') : '#e8edf2 0 100%'; $(id).style.background = `conic-gradient(${gradient})`; }
function renderLegend(id, parts) { $(id).innerHTML = parts.map((part) => `<span><i style="background:${part.color}"></i>${part.label} <b>${part.value}</b></span>`).join(''); }
function renderSubnetChart(subnets) { const max = Math.max(...subnets.map((item) => item.total), 1); $('subnet-chart').innerHTML = subnets.slice(0, 18).map((item) => `<div class="bar-row"><span>${escapeHtml(item.subnet)}</span><div class="bar-track"><i style="width:${item.total / max * 100}%"><b>${item.total}</b></i></div><small>${item.online} online</small></div>`).join('') || '<p class="empty-state">No subnet data available.</p>'; }
function renderSubnets() { const rows = groupedSubnets(); $('subnet-table').innerHTML = `<div class="table-scroll"><table><thead><tr><th>Subnet</th><th>Used IPs</th><th>Online</th><th>Offline</th><th>Unknown</th><th>Utilization</th><th>Locations</th></tr></thead><tbody>${rows.map((row) => `<tr><td><strong>${escapeHtml(row.subnet)}</strong></td><td>${row.total}</td><td><span class="text-online">${row.online}</span></td><td><span class="text-offline">${row.offline}</span></td><td>${row.unknown}</td><td><div class="mini-progress"><i style="width:${Math.min(row.total / 254 * 100, 100)}%"></i></div><small>${Math.round(row.total / 254 * 100)}%</small></td><td>${escapeHtml([...new Set(row.devices.map((device) => device.location_or_point).filter(Boolean))].slice(0, 3).join(', ') || '—')}</td></tr>`).join('')}</tbody></table></div>`; }
function filteredDevices() { const search = state.ipSearch.trim().toLowerCase(); return state.devices.filter((device) => (state.ipStatus === 'all' || device.status === state.ipStatus) && (!search || [device.ip_address, device.device_name, device.user_name, device.location_or_point].join(' ').toLowerCase().includes(search))); }
function renderIps() { const devices = filteredDevices(); $('ip-table').innerHTML = `<div class="table-scroll"><table><thead><tr><th>Status</th><th>IP address</th><th>Device</th><th>User</th><th>Subnet</th><th>Location</th><th>Last checked</th><th>Actions</th></tr></thead><tbody>${devices.length ? devices.map((device) => `<tr><td>${statusPill(device.status)}</td><td><strong class="mono">${escapeHtml(device.ip_address)}</strong></td><td>${escapeHtml(device.device_name)}</td><td>${escapeHtml(device.user_name)}</td><td>${escapeHtml(subnetOf(device.ip_address))}</td><td>${escapeHtml(device.location_or_point)}</td><td>${formatShortDate(device.last_ping_at)}</td><td><div class="row-actions"><button class="text-button" data-action="ping" data-id="${device.id}">Ping</button><button class="text-button" data-action="edit" data-id="${device.id}">Edit</button><button class="text-button danger" data-action="delete" data-id="${device.id}">Delete</button></div></td></tr>`).join('') : '<tr><td colspan="8" class="empty-state">No IP records match this view.</td></tr>'}</tbody></table></div>`; }
function renderHistory() { $('history-table').innerHTML = `<div class="table-scroll"><table><thead><tr><th>Time</th><th>IP address</th><th>Device</th><th>Previous</th><th>Current</th><th>Message</th></tr></thead><tbody>${state.history.length ? state.history.slice().reverse().map((item) => `<tr><td>${formatShortDate(item.time)}</td><td class="mono">${escapeHtml(item.ip)}</td><td>${escapeHtml(item.name)}</td><td>${statusPill(item.previous)}</td><td>${statusPill(item.current)}</td><td>${escapeHtml(item.message)}</td></tr>`).join('') : '<tr><td colspan="6" class="empty-state">Status changes will appear here after monitoring updates.</td></tr>'}</tbody></table></div>`; }
function renderAlerts() { const alerts = state.devices.filter((device) => device.status === 'offline'); $('alerts-table').innerHTML = `<div class="table-scroll"><table><thead><tr><th>Severity</th><th>IP address</th><th>Device</th><th>Location</th><th>Down since</th><th>Action</th></tr></thead><tbody>${alerts.length ? alerts.map((device) => `<tr><td><span class="alert-severity">Offline</span></td><td class="mono">${escapeHtml(device.ip_address)}</td><td>${escapeHtml(device.device_name)}</td><td>${escapeHtml(device.location_or_point)}</td><td>${formatShortDate(device.down_since)}</td><td><button class="text-button" data-action="ping" data-id="${device.id}">Check now</button></td></tr>`).join('') : '<tr><td colspan="6" class="empty-state">No active alerts. Network is looking calm.</td></tr>'}</tbody></table></div>`; }
function renderAll() { updateMetrics(); renderSubnets(); renderIps(); renderHistory(); renderAlerts(); }
async function loadDevices({ showLoading = true } = {}) { try { if (showLoading && !state.devices.length) $('ip-table').innerHTML = '<div class="loading-state">Loading IP inventory...</div>'; const devices = await fetchJson('/api/devices'); const signature = JSON.stringify(devices); const now = new Date().toISOString(); devices.forEach((device) => { const previous = state.previousStatuses.get(device.id); if (previous && previous !== device.status) state.history.push({ time: now, ip: device.ip_address, name: device.device_name, previous, current: device.status, message: `Device changed from ${previous} to ${device.status}` }); state.previousStatuses.set(device.id, device.status); }); state.devices = devices; if (state.deviceSignature !== signature) { state.deviceSignature = signature; renderAll(); } else updateMetrics(); elements.lastUpdated.textContent = formatDateTime(now); elements.indicator.classList.remove('offline'); elements.connectionLabel.textContent = 'Live monitoring'; } catch (error) { elements.indicator.classList.add('offline'); elements.connectionLabel.textContent = 'Connection issue'; if (!state.devices.length) $('ip-table').innerHTML = `<div class="empty-state">Unable to load inventory. ${escapeHtml(error.message)}</div>`; } }
async function refreshDashboard({ silent = false } = {}) { if (state.refreshInProgress) return; state.refreshInProgress = true; elements.refreshButton.disabled = true; try { await loadDevices({ showLoading: !silent }); } finally { state.refreshInProgress = false; elements.refreshButton.disabled = false; } }
function startAutoRefresh() { clearInterval(state.refreshTimer); state.refreshTimer = setInterval(() => refreshDashboard({ silent: true }), 10000); }
function switchTab(tab) { state.activeTab = tab; document.querySelectorAll('.tab').forEach((button) => button.classList.toggle('active', button.dataset.tab === tab)); document.querySelectorAll('.view').forEach((view) => view.classList.toggle('active-view', view.id === `${tab}-view`)); if (tab === 'ips') renderIps(); }
function openDeviceModal(device = null) { elements.formStatus.textContent = ''; elements.deviceForm.reset(); state.editDeviceId = device ? device.id : null; elements.modalTitle.textContent = device ? 'Edit Device' : 'Add Device'; $('device-name').value = device?.device_name || ''; $('user-name').value = device?.user_name || ''; $('ip-address').value = device?.ip_address || ''; $('location').value = device?.location_or_point || ''; $('notes').value = device?.notes || ''; $('is-active').checked = device ? !!device.is_active : true; elements.deviceModal.classList.add('open'); }
function closeModal(modal) { $(modal).classList.remove('open'); }
function openDeleteModal(id, name) { elements.deleteId.value = id; elements.deleteName.textContent = name; elements.deleteModal.classList.add('open'); }
async function submitDeviceForm(event) { event.preventDefault(); const payload = { device_name: $('device-name').value.trim(), user_name: $('user-name').value.trim(), ip_address: $('ip-address').value.trim(), location_or_point: $('location').value.trim(), notes: $('notes').value.trim(), is_active: $('is-active').checked }; try { await fetchJson(state.editDeviceId ? `/api/devices/${state.editDeviceId}` : '/api/devices', { method: state.editDeviceId ? 'PUT' : 'POST', body: JSON.stringify(payload) }); closeModal('device-modal'); state.deviceSignature = null; await refreshDashboard(); } catch (error) { elements.formStatus.textContent = error.message; } }
async function deleteDevice() { const id = Number(elements.deleteId.value); if (!id) return; try { await fetchJson(`/api/devices/${id}`, { method: 'DELETE' }); closeModal('delete-confirm-modal'); state.deviceSignature = null; await refreshDashboard(); } catch (error) { alert(error.message); } }
async function pingDevice(id) { try { await fetchJson(`/api/devices/${id}/ping`, { method: 'POST' }); state.deviceSignature = null; await refreshDashboard(); } catch (error) { alert(error.message || 'Ping failed'); } }
function bindEvents() { document.querySelectorAll('[data-tab]').forEach((button) => button.addEventListener('click', () => switchTab(button.dataset.tab))); elements.refreshButton.addEventListener('click', () => refreshDashboard()); elements.addDeviceButton.addEventListener('click', () => openDeviceModal()); elements.deviceForm.addEventListener('submit', submitDeviceForm); $('cancel-device').addEventListener('click', () => closeModal('device-modal')); $('cancel-delete').addEventListener('click', () => closeModal('delete-confirm-modal')); $('confirm-delete').addEventListener('click', deleteDevice); elements.ipSearch.addEventListener('input', (event) => { state.ipSearch = event.target.value; renderIps(); }); elements.ipStatus.addEventListener('change', (event) => { state.ipStatus = event.target.value; renderIps(); }); document.querySelectorAll('[data-close]').forEach((button) => button.addEventListener('click', () => closeModal(button.dataset.close))); document.addEventListener('click', (event) => { const button = event.target.closest('[data-action]'); if (!button) return; const id = Number(button.dataset.id); const device = state.devices.find((item) => item.id === id); if (button.dataset.action === 'ping') pingDevice(id); if (button.dataset.action === 'edit' && device) openDeviceModal(device); if (button.dataset.action === 'delete' && device) openDeleteModal(id, device.device_name); }); }
async function init() { bindEvents(); await refreshDashboard(); startAutoRefresh(); }
init();